### ISSUE TITLE
Derive requires direct dependency on `parity-scale-codec`

### ISSUE THREAD

**Issue by ascjones** [paritytech/scale-info#68]
Discussed [here](https://github.com/paritytech/parity-common/pull/519#issuecomment-779863300) and [here](https://github.com/paritytech/scale-info/pull/61#discussion_r568760753).

Using the derive crate assumes a direct dependency on `parity-scale-codec` from the user's crate. Brainstorming ideas:

-  as [Basti suggests](https://github.com/paritytech/scale-info/pull/61#discussion_r568760753) do a reexport of the required types (see comment)
- better error message if the crate is not present
- add a feature `"compact"` or so to enable that functionality for which the codec types are required.
- make the macro determine whether any compact fields are present and only import the lib.

This also feeds into the larger discussion about how these two libraries coexist, and to what extent they should be coupled.

/cc @Robbepop @dvdplm @ordian

**Comment by dvdplm** [comment]
> and to what extent they should be coupled.

I think they de facto are coupled already and likely has to be, to be able to achieve its mid-/long-term goals. 

Special-caseing "compact" is a bit yucky and is a slippery slope: we'll need other attributes as well (`encode_as`, `index` and `skip`) and we've recently made the decision to rely on end-users annotating e.g. `PhantomData` fields with `#[codec(skip)]` rather than adding an "ignore" attribute to `scale-info` itself.

I think the mid-term solution is to integrate the two crates into one; maybe it's not very satisfying intellectually but it **is** pragmatic.

In the short term I second @bkchr's suggestion to re-export the required types.

**Comment by bkchr** [comment]
Yeah, I expressed my preferences :D 



> I think the mid-term solution is to integrate the two crates into one; maybe it's not very satisfying intellectually but it **is** pragmatic.

You are right that they don't fit perfectly. However, I'm with you that we should merge them. We will probably hide `scale-info` behind some feature, but in the end we probably want scale-info without putting an extra derive above each type :)
